### ISSUE TITLE
compose.yaml og Dockerfile

### ISSUE THREAD

**Issue by sshine** [tgavri/guessr#29]
Det skal kunne lade sig gøre at skrive `docker compose build` og `docker compose up`.

For at det lader sig gøre, skal I have en `compose.yaml` og en `Dockerfile`.

I kan benytte `Dockerfile` som blev brugt i de to første individuelle afleveringsopgaver.

Den er generisk for Java-projekter med Maven og bygger projektet i to faser (multi-stage builds).

En skabelon til compose.yaml uden MySQL-understøttelse:

```yaml
services:
  jeres-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./src/main/resources/application.properties:/app/application.properties:ro
    environment:
      - SPRING_CONFIG_LOCATION=classpath:/,file:/app/application.properties
```

Det er fint nok at jeres applikation ikke kører MySQL. Det er ikke et krav til compose.yaml.

Linjen `./src/main/resources/application.properties:/app/application.properties:ro` virker hvis man står i jeres projektmappe når man skriver `docker compose up`: I et realistisk scenario vil man også ønske at kunne starte sine containere selvom man ikke har kildekoden tilgængelig, og man vil måske derfor gerne skrive noget andet end `./src/...`, da den application.properties man kan forestille sig at bruge i produktion ligger i en bestemt mappe på ens server. Det er ikke så vigtigt for afleveringen, men det giver mening at vide, hvis man har tænkt sig at deploye sin Java-app på en server.

I kan også tilføje en MySQL-container i compose.yaml, hvis I vil. Det er dog valgfrit.

## Delopgaver

- [x] Kopier Dockerfile ind
- [x] Lav compose.yaml
- [x] Tjek at `docker compose build` virker
- [x] Lav pull request og tilføj mig som reviewer
